### ISSUE TITLE
Cannot find module 'jhipster-core' error

### ISSUE THREAD

**Issue by poolebu** [Magillem/generator-jhipster-pages#12]
Hello I'm trying version `generator-jhipster-pages@2.0.2` with `"jhipsterVersion": "4.13.3"` after updating to fix the #11 issue. It now gives me this error:

```
Ernestos-MacBook-Pro-3:testPages poolebu$ yo jhipster-pages
module.js:472
    throw err;
    ^

Error: Cannot find module 'jhipster-core'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/poolebu/.npm-packages/lib/node_modules/generator-jhipster-pages/generators/app/prompts.js:23:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

What should I try ? Thank you!

**Comment by Dufgui** [comment]
hello,

jhipser-core is available:
https://www.npmjs.com/package/jhipster-core
So i think yeoman miss the dependancy install during the upgrade of pages modules.
So you must go in the install path of the module:
/Users/poolebu/.npm-packages/lib/node_modules/generator-jhipster-pages/
and try a `yarn install` or `npm install`

I hope it solve the problem. If not, please check if jhipster-core is present in /Users/poolebu/.npm-packages/lib/node_modules/generator-jhipster-pages/node_modules
